export const ROUTES = {
  about: "/about-us",
  regulations: "/our-regulations",
  contacts: "/contacts",
  delivery: "/delivery-and-paymen",
  credit: "/credit",
  warranty: "/warranty",
  goodsReturn: "/goods-return",
  serviceCenters: "/service-centers",
  bonusAccount: "/bonus-account",
  rozetkaPremium: "/rozetka-premium",
  giftCertificates: "/gift-certificates",
  rozetkaExchange: "/rozetka-exchange",
  tours: "/tours-and-vacations",
  sales: "/sales",
  partnership: "/partnership",
  franchising: "/franchising",
  rental: "/rental",
};
