import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
        <p className={styles.banner}>Banner</p>
        <nav className={styles.nav}>This is navbar</nav>
      </header>

      <main className={styles.main}>
        <h1 className={styles.title}>E-market application</h1>
      </main>

      <footer className={styles.footer}>
        <p>This is footer</p>
      </footer>
    </div>
  );
};

export default Home;
